import type { Metadata } from "next";
import "./globals.css";
import { LoadingProvider } from "@/components/LoadingContext";
import Loading from "@/components/Loading";
import { NavigationEvents } from "@/components/NavigationEvents";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <LoadingProvider>
          <Loading />
          {children}
          <NavigationEvents />
        </LoadingProvider>
      </body>
    </html>
  );
}